/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HRD;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DOSTAKIJO
 */
public class Dashboard_Kelola_Data_Pegawai extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard_Data_Pegawai
     */
    public Dashboard_Kelola_Data_Pegawai() {
        initComponents();
        tampilkanDataUserPegawai();
    }
    
    private void tampilkanDataUserPegawai() {
        try {
            Connection conn = Admin.DatabaseConnection.connect();
            String sql = "SELECT * FROM users WHERE Jabatan = 'pegawai'";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No");        // Nomor urut lokal, bukan ID dari DB
            model.addColumn("Username");
            model.addColumn("Password");
            model.addColumn("Akses");
            model.addColumn("Status");

            int no = 1;
            while (rs.next()) {
                model.addRow(new Object[]{
                    no++,
                    rs.getString("Username"),
                    rs.getString("Password"),
                    rs.getString("Akses"),
                    rs.getString("Status")
                });
            }

            jTable1.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
        }
    }



    
    private void resetAutoIncrement(String namaTabel) {
        if (namaTabel == null || namaTabel.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "❌ Nama tabel tidak valid untuk reset!");
            return;
        }

        try (Connection conn = DatabaseConnection.connect();
             Statement stmt = conn.createStatement()) {

            stmt.executeUpdate("DROP TABLE IF EXISTS temp_" + namaTabel);
            stmt.executeUpdate("CREATE TABLE temp_" + namaTabel + " AS SELECT * FROM " + namaTabel);
            stmt.executeUpdate("DELETE FROM " + namaTabel);
            stmt.executeUpdate("ALTER TABLE " + namaTabel + " AUTO_INCREMENT = 1");

            String queryInsert;
            if (namaTabel.equals("users")) {
                queryInsert = "INSERT INTO " + namaTabel + " (Username, Password, Akses, Jabatan, Status, Gaji) " +
                              "SELECT Username, Password, Akses, Jabatan, Status, Gaji FROM temp_" + namaTabel;
            } else {
                queryInsert = "INSERT INTO " + namaTabel + " (Username, Password, Akses, Status) " +
                              "SELECT Username, Password, Akses, Status FROM temp_" + namaTabel;
            }

            stmt.executeUpdate(queryInsert);
            stmt.executeUpdate("DROP TABLE temp_" + namaTabel);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "❌ Gagal merapikan ID: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Search : ");

        jButton1.setText("GO ⇨");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("PECAT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Lihat Data Pegawai");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("⇦  BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Data Pegawai");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    String keyword = jTextField1.getText().trim();

    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "⚠️ Masukkan username yang ingin dicari.");
        return;
    }

    DefaultTableModel modelLama = (DefaultTableModel) jTable1.getModel();
    DefaultTableModel modelBaru = new DefaultTableModel();

    modelBaru.addColumn("No");
    modelBaru.addColumn("Username");
    modelBaru.addColumn("Password");
    modelBaru.addColumn("Akses");
    modelBaru.addColumn("Status");

    boolean ditemukan = false;

    for (int i = 0; i < modelLama.getRowCount(); i++) {
        String username = modelLama.getValueAt(i, 1).toString(); // kolom Username (No = 0, Username = 1)

        if (username.toLowerCase().contains(keyword.toLowerCase())) {
            Object[] row = new Object[5];
            row[0] = modelLama.getValueAt(i, 0); // No lokal (jangan diubah)
            row[1] = modelLama.getValueAt(i, 1); // Username
            row[2] = modelLama.getValueAt(i, 2); // Password
            row[3] = modelLama.getValueAt(i, 3); // Akses
            row[4] = modelLama.getValueAt(i, 4); // Status

            modelBaru.addRow(row);
            ditemukan = true;
        }
    }

    if (!ditemukan) {
        JOptionPane.showMessageDialog(this, "❌ Username tidak ditemukan.");
        return;
    }

    jTable1.setModel(modelBaru);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            resetAutoIncrement("users");  // Tetap reset ID tabel users

            Connection conn = DatabaseConnection.connect();
            String query = "SELECT Username, Password, Akses, Status FROM users WHERE Jabatan = 'pegawai' ORDER BY ID";
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No"); // Ganti ID jadi Nomor lokal
            model.addColumn("Username");
            model.addColumn("Password");
            model.addColumn("Akses");
            model.addColumn("Status");

            int no = 1; // Mulai dari 1
            while (rs.next()) {
                model.addRow(new Object[]{
                    no++,  // Nomor urut
                    rs.getString("Username"),
                    rs.getString("Password"),
                    rs.getString("Akses"),
                    rs.getString("Status")
                });
            }

            jTable1.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Gagal menampilkan data pegawai: " + e.getMessage());
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "❗ Pilih pegawai yang ingin dipecat.");
            return;
        }

        String username = jTable1.getValueAt(selectedRow, 1).toString(); // Kolom Username

        // Konfirmasi
        int opt = JOptionPane.showConfirmDialog(this,
                "Yakin ingin memecat pegawai \"" + username + "\" ?",
                "Konfirmasi Pemecatan", JOptionPane.YES_NO_OPTION);
        if (opt != JOptionPane.YES_OPTION) return;

        try (Connection conn = Admin.DatabaseConnection.connect()) {

            // Pastikan jabatan memang pegawai
            PreparedStatement cek = conn.prepareStatement(
                    "SELECT Jabatan FROM users WHERE Username = ?");
            cek.setString(1, username);
            ResultSet rs = cek.executeQuery();

            if (!rs.next() || !rs.getString("Jabatan").equalsIgnoreCase("pegawai")) {
                JOptionPane.showMessageDialog(this,
                        "❌ Hanya pegawai biasa yang bisa dipecat!");
                return;
            }

            // Hapus pegawai
            PreparedStatement del = conn.prepareStatement(
                    "DELETE FROM users WHERE Username = ? AND Jabatan = 'pegawai'");
            del.setString(1, username);
            del.executeUpdate();

            // Reset ID fisik tabel users
            resetAutoIncrement("users");

            // Refresh tampilan
            tampilkanDataUserPegawai();

            JOptionPane.showMessageDialog(this,
                    "✅ Pegawai \"" + username + "\" berhasil dipecat.\nID di tabel telah di‑reset.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Gagal memecat pegawai: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new HRD.Dashboard_HRD().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Kelola_Data_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Kelola_Data_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Kelola_Data_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Kelola_Data_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Kelola_Data_Pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
